# Dependencies: In Practice

NB We copy/pasted the previous book club part on dependencies from 1ed to the correct chapter from 2ed but we have not processed it.  

**Learning objectives:**

- THESE ARE NICE TO HAVE BUT NOT ABSOLUTELY NECESSARY

## Dependencies

The `DESCRIPTION` file lists the packages that your package needs to work.

### `Imports`

- **Must** be present at runtime
  - Automatically installs missing packages when your package is installed
  - `devtools::load_all()` checks too
  - Installed but not attached; to attach, use `package::function()` within package

```
Imports:
    dplyr,
    tidyr
```

### `Suggests`

- Your package *can* use these packages, but doesn’t require them
  - "Isn’t terribly relevant for packages where the user base is approximately equal to the development team"
  - Does not automatically install missing packages when your package is installed
  - Add for development tasks or to unlock additional functionality (run tests, build vignettes / examples) or rarely needed packages or tricky packages

```r
Suggests:
    ggplot2,
    testthat
```

#### Guarding use of suggested packages

Or, how to write functions in your package with suggested packages in a way that won't cause issues for your users

- Use `requireNamespace("pkg", quietly = TRUE)`, which tries to load "pkg". If a package isn’t installed, loading will fail with an error
- rlang has some functions to do the below with other handy features

1) Stop function if it cannot load the package and send a message to install package

```
# the suggested package is required 
my_fun <- function(a, b) {
  if (!requireNamespace("pkg", quietly = TRUE)) {
    stop(
      "Package \"pkg\" must be installed to use this function.",
      call. = FALSE
    )
  }
  # code that includes calls such as pkg::f()
}
```

2) Escape part that needs the package and do something else
  - If package is installed, then package will be loaded and run `pkg::f()`
  - If it is not installed, it will fail to load, escape first part of if-else statement, and run `g()`
  
```
# the suggested package is optional; a fallback method is available
my_fun <- function(a, b) {
  if (requireNamespace("pkg", quietly = TRUE)) {
    pkg::f()
  } else {
    g()
  }
}
```

**About `requireNamespace()`**

Can also use `require()` for examples

- From Chapter 13: `require()` loads and attaches; `requireNamespace()` just loads
- `requireNamespace()` will fail if package is not installed; use it if that is when you want your script to fail; use `require()` want to use the package for something
- An example is basically the only place where we would use `require()` inside a package
  - [Pretty good Reddit thread](https://www.reddit.com/r/rstats/comments/5qtib2/what_is_the_difference_between_require_and/)
  
**Tests**

In tests, it is not as necessary to guard the use of a suggested package

- The tidyverse team assumes the package is available
- They should be caught by `R CMD check`

But if you really want to guard the use of them in a test, you can use `testthat::skip_if_not_installed()`. In the case below, it is because installing sf can be difficult and skipping this test allows the user to run the other tests.

```r
test_that("basic plot builds without error", {
  skip_if_not_installed("sf")

  nc_tiny_coords <- matrix(
    c(-81.473, -81.741, -81.67, -81.345, -81.266, -81.24, -81.473,
      36.234, 36.392, 36.59, 36.573, 36.437, 36.365, 36.234),
    ncol = 2
  )

  nc <- sf::st_as_sf(
    data_frame(
      NAME = "ashe",
      geometry = sf::st_sfc(sf::st_polygon(list(nc_tiny_coords)), crs = 4326)
    )
  )

  expect_doppelganger("sf-polygons", ggplot(nc) + geom_sf() + coord_sf())
})
```

### `Depends`

Use `Depends`, `LinkingTo`, and `Enhances` for more specialized dependencies.

- Do not use for packages, use `Imports` instead (Chapter 13 spoiler: `Depends` loads and attaches the package whereas `Imports` just loads it)
- Can be used to set a minimum version of R: `R (>= 4.0.0)`
  - If you state a minimum of R, you should have a reason and you should take reasonable measures to test your claim regularly
  
**An R version gotcha**

* `saveRDS()` used version 2 for twenty years
* Version 3 became the default in 2019 with R 3.6.0
* Older packages with version 2 `.rds` files were rebuilt with version 3 and  require R version 3.5.0 or above
* Bundled and source package different!
* All packages listing the original package in `Imports` or even `Suggests` inherit new dependency
* The more dependencies, the more thought to minimum versions

### `LinkingTo`

- Packages listed here rely on C or C++ code in another package

### `Enhances`

- Provide methods for classes defined in another package
- Not recommended

### `Remotes`

- Installs dependencies from outside of CRAN or Bioconductor
  - Nonstandard dependencies are not allowed in CRAN submissions
- Written similar to `Imports`

```
Remotes: hadley/testthat
```

### `Config/Needs/`

- Usually associated with continuous integration workflows (e.g., to build a website)
  - New edition will cover this more fully
- Ignored by CRAN
- Specialized task dependencies vs true runtime dependencies

### How to write fields

- Comma-separated
- One package per line
- Alphabetical
- Add with `usethis::use_package(package, type = "Imports")` & `usethis::use_package(package, type = "Suggests")`
- Use `usethis::use_tidy_description()` to put fields in standard order and alphabetize dependencies
- Write minimum versions in parenthesis after package name `dplyr (>= 1.0.0)`. Make sure it is a *minimum* not an *exact* version.


## SLIDE 1

- ADD SLIDES AS SECTIONS (`##`).
- TRY TO KEEP THEM RELATIVELY SLIDE-LIKE; THESE ARE NOTES, NOT THE BOOK ITSELF.

## Meeting Videos

### Cohort 1

`r knitr::include_url("https://www.youtube.com/embed/C_H1oQZD7m8")`


### Cohort 2

`r knitr::include_url("https://www.youtube.com/embed/8PU_KT5IpWg")`


### Cohort 3

`r knitr::include_url("https://www.youtube.com/embed/2-baO_E9p1s")`

<details>
<summary> Meeting chat log </summary>

```
00:05:44	Ryan Metcalf:	https://www.rstudio.com/conference/
00:08:38	Brendan Lam:	https://stackoverflow.com/questions/70097126/how-to-edit-namespace-with-roxygen2-when-creating-r-packages
00:08:51	Brendan Lam:	https://stackoverflow.com/questions/11990589/r-namespace-access-and-match-fun
00:44:59	Rex Parsons:	https://github.com/gentrywhite/DSSP/blob/b3d7f0d10374968a43a634a1ae3f65e9231fceb0/R/plot.R#L43
00:48:01	Rex Parsons:	https://stackoverflow.com/questions/5595512/what-is-the-difference-between-require-and-library
00:58:13	Rex Parsons:	gotta run guys - thanks Brendan and team!
00:58:29	collinberke:	https://stackoverflow.com/questions/64737686/why-library-or-require-should-not-be-used-in-a-r-package
```
</details>


<!--
### Cohort 4

`r knitr::include_url("https://www.youtube.com/embed/VIDURL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
-->


<!--
### Cohort 5

`r knitr::include_url("https://www.youtube.com/embed/VIDURL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
-->
