# (PART) Maintenance and distribution {-}

# Software development practices
**Goal**: zoom back now and consider software development practices

- More productive  
- Raise quality of work  
- More reproducibility

## Recommendations 

- An IDE with support for R package development  (Usually RStudio)

- Version control (Git) + Hosted version control (GitHub)

- Continuous Integration / Continuous Deployment: Mostly automatic `R CMD check`

Pros: 

- Do the right thing: **experiment, document, test, check, collaborate**

- Use the same tools/workflows as experts

## Git and Github

Git manages the evolution of a set of files (repository).

- 94 % of VC is Git

- GitHub is dominant, followed by GitLab and Bitbucket

- Lot of resources: [Happy git and Github for the useR](https://cran.r-project.org/web/packages/validate/vignettes/cookbook.html)

It allows: 

- Communications with users (Issues)

- Collaboration (PR, feature requests)

- Distribution (`devtools::install_github`) or now with `pak` install specific SHA

(SHA-1 is used by Git instead of adding numbers, Secure Hash Algorithms)

- Website: see `pkgdown`  

## CI/CD

For a package: 

1. Source package in GH  
    * Multiple developers have permissions to push   
    * External developers can push via PR
    
2. Main idea: development tasks can be executed automatically when certain events happen

Example: Automate R `CMD check` (runs checks remotely, on various OS's)


## More GitHub Actions (GHA)

`usethis` has functions that copy GHA workflows into a specific folder `.github`.

You have a curated already made workflow here : https://github.com/r-lib/actions/#readme

When using `usethis::use_github_action_check_standard()`

```
#> ✔ Creating '.github/'
#> ✔ Adding '*.html' to '.github/.gitignore'
#> ✔ Creating '.github/workflows/'
#> ✔ Saving 'r-lib/actions/examples/check-standard.yaml@v2' to .github/workflows/R-CMD-check.yaml'
#> • Learn more at <https://github.com/r-lib/actions/blob/v2/examples/README.md>.
#> ✔ Adding R-CMD-check badge to 'README.md'```
```

* Create `.github/workflow/`

* Add new needed lines in `.gitignore`

* Add a shiny badge at the top of your README.md

It has plenty of other uses! 

- `usethis::use_pkgdown_github_page()`

- `usethis::use_github_action("test_covergae")`

## More info and examples

[Rendering and re-publishing the R Packages book!](https://github.com/hadley/r-pkgs/blob/main/.github/workflows/render.yaml)
[Quarto-specific workflows](https://github.com/quarto-dev/quarto-actions?tab=readme-ov-file)
[A reminder of all the checks contained in R CMD check](https://r-pkgs.org/R-CMD-check.html#:~:text=R%20CMD%20check%20runs%20R,debug%20any%20problems%20before%20continuing.)
[Workflow YAML syntax](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions)

## Meeting Videos

This was a somewhat different chapter for cohorts 1-3.

### Cohort 1

`r knitr::include_url("https://www.youtube.com/embed/SHAdJmjvQ44")`

`r knitr::include_url("https://www.youtube.com/embed/RlE8P3f10ZU")`


### Cohort 2

`r knitr::include_url("https://www.youtube.com/embed/pedUcPFrZMQ")`


### Cohort 3

`r knitr::include_url("https://www.youtube.com/embed/LkSKXeZTD-0")`

<details>
<summary> Meeting chat log </summary>

```
00:29:06	Ryan Metcalf:	https://blog.jdriven.com/2020/10/automating-hosting-revealjs-slides-on-gitlab/
00:53:57	Arun Chavan:	https://rstudio.github.io/distill/website.html
00:55:46	Brendan Lam:	Cool! I didn’t even remember what's on my repo
01:05:13	Brendan Lam:	As someone who didn't know what Docker is, this was very informative. thanks, Ryan!
```
</details>


### Cohort 4

`r knitr::include_url("https://www.youtube.com/embed/hbh7SF_ffhM")`
