--- 
title: "R Packages Book Club"
author: "The R4DS Online Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-rpkgs
description: "This is the product of the R4DS Online Learning Community's R Packages Book Club."
---

# Welcome {-}

Welcome to the bookclub! 

This is a companion for the book [_R Packages_](https://r-pkgs.org/) by Hadley Wickham and Jenny Bryan (work-in-progress 2nd edition, copyright 2022).
This companion is available at [r4ds.io/rpkgs](https://r4ds.io/rpkgs).

This website is being developed by the [R4DS Online Learning Community](https://rfordatasci.com). Follow along, and [join the community](https://r4ds.io/join) to participate.

This companion follows the [R4DS Online Learning Community Code of Conduct](https://r4ds.io/conduct).

## Book club meetings {-}

- Each week, a volunteer will present a chapter from the book (or part of a chapter).
  - **This is the best way to learn the material.**
- Presentations will usually consist of a review of the material, a discussion, and/or a demonstration of the principles presented in that chapter.
- More information about how to present is available in the [github repo](https://github.com/r4ds/bookclub-rpkgs).
- Presentations will be recorded, and will be available on the [R4DS Online Learning Community YouTube Channel](https://r4ds.io/youtube).
- Camera is optional, but encouraged.
- If we need to slow down and discuss, let me know
   - Most likely someone has the same question 
   - We are all here to learn 

## Pace {-}

- We'll _try_ to cover 1 chapter/week, but...
- ...It's ok to split chapters when they feel like too much.
- We will try to meet every week, but will likely take some breaks for holidays, etc.
- The sessions will be exactly one hour.  
- I encourage the group to adopt a 'go no matter what' mentality.

## Introductions {-}

- If you feel comfortable sharing:
   - Who are you?
   - Where are you calling in from?
   - How long have you been using R?
   - What are you most looking forward to during the group?

## git and GitHub {-}

* It's worth taking the time to learn `git` and version control.
* It's a topic discussed more in-depth later in the book. 
* If you lead the discussion, it's best to integrate your materials into this `bookdown` version of the materials.
* You'll need a `GitHub` account to submit any modifications.

#### If you're comfortable with `git` and GitHub {-}

* Fork the repo to your account.
* Create a branch to make your changes.
* Submit a pull request via the `R4DS` repo for the book
* PR's will are reviewed before being pushed and knitted

## Questions for the group {-}

#### Question 1 {-}

Question 1 for the group (submit answers to the chat)

On a scale from 1 - 5, how familiar are you with using `git` for version control?

1 = Not at all familiar (a true beginner)

to

5 = Very familiar (use `git` everyday/can handle a merge conflict like a pro)

#### Question 2 for the group {-}

On a scale from 1 - 5, how familiar are you with using GitHub?

1 = Not at all familiar (a true beginner)

to 

5 = Very familiar (I have GitHub account with repositories)

#### Optional Question 3 (depending on feedback) {-}

On a scale from 1 - 5, how valuable would it be to devote a week to introducing `git` and GitHub?

1 = Not at all valuable

to 

5 = Very valuable

## Resources to learn more about `git` and GitHub {-}

* [Happy Git and GitHub for the useR](https://happygitwithr.com/)
* [`usethis`'s pull request helpers](https://usethis.r-lib.org/articles/pr-functions.html)
* [`git`'s documentation](https://git-scm.com/doc)
* [MShiny Cohort 2 Introduction](https://www.youtube.com/watch?v=beOYuHG9Xng&list=PL3x6DOfs2NGjhwrYvdmrKRNcvXX7X6ldt)
* [Git for Book Clubs YouTube playlist](https://www.youtube.com/playlist?list=PL3x6DOfs2NGhS_PhklqT6PwK1Fh7blgP2)

